services:
  web:
    build: .
    command: >
      sh -c "ls -la /app && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${WEB_PORT:-8000}"
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT:-8000}:${WEB_PORT:-8000}"
    env_file:
      - .env
    depends_on:
      - celery

  celery:
    build: .
    command: celery -A ${APP_NAME:-credit_approval}.celery worker --loglevel=${LOG_LEVEL:-info} --pool=solo
    volumes:
      - .:/app
    env_file:
      - .env
